// This class is autogenerated! See slks_make_redirects.sh
namespace XRL.World.Parts.Mutation {
  [System.Serializable]
  public class SLKS_FrostCondensation : StarlitKaleidoscope.Parts.Mutations.FrostCondensation {}
}
