// This class is autogenerated! See slks_make_redirects.sh
namespace XRL.World.Parts.Mutation {
  [System.Serializable]
  public class SLKS_StaticBurst : StarlitKaleidoscope.Parts.Mutations.StaticBurst {}
}
