// This class is autogenerated! See slks_make_redirects.sh
namespace XRL.World.Parts {
  [System.Serializable]
  public class SLKS_FrostCondensationOnHit : StarlitKaleidoscope.Parts.Generic.FrostCondensationOnHit {}
}
